Repository 2k1-Pinequest/Quest, pull requests merged in 2025-09, with the labels that each got.

#29 studentDashboard
  client/package-lock.json
  client/package.json
  client/src/app/studentRoom/page.tsx
  client/src/components/student/studentQuiz.tsx
  client/src/components/ui/dropdown-menu.tsx
  client/src/components/ui/textarea.tsx
Labels: FrontEnd, PineQuest

#30 added student dashboard component
  client/src/app/studentRoom/page.tsx
  client/src/components/student/StudentDashboard.tsx
Labels: FrontEnd, PineQuest

#35 FrontendStudent
  client/package-lock.json
  client/src/app/studentRoom/page.tsx
  client/src/components/student/studentQuiz.tsx
Labels: FrontEnd, PineQuest

#37 createTeacher createRoom
  server/package-lock.json
  server/package.json
  server/src/controllers/CreateRoom.ts
  server/src/controllers/room/createRoom.controller.ts
  server/src/controllers/teacher/createTeacher.controller.ts
  server/src/index.ts
  server/src/routes/createTeacher.ts
  server/src/routes/room-routes.ts
Labels: documentation, PineQuest, BackEnd

#40 Student dashboard with submit section done
  client/package-lock.json
  client/package.json
  client/src/app/globals.css
  client/src/app/studentRoom/page.tsx
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentJoin.tsx
  client/src/components/student/studentQuiz.tsx
Labels: FrontEnd, PineQuest

#45 zaswar
  server/src/routes/createTeacher.ts
Labels: documentation, PineQuest, BackEnd

#46 student joinroom test
  server/src/controllers/room/createRoom.controller.ts
  server/src/controllers/student/joinRoom.controller.ts
  server/src/index.ts
  server/src/routes/student-routes.ts
Labels: student, PineQuest, BackEnd

#48 server client holbolt
  client/src/app/sign-in/page.tsx
  client/src/app/sign-up/page.tsx
  client/src/components/auth/sign-in.tsx
  client/src/components/auth/sign-up.tsx
Labels: documentation, FrontEnd, PineQuest

#50 back cors
  server/src/index.ts
  server/src/routes/createTeacher.ts
  server/src/routes/student-routes.ts
Labels: documentation, PineQuest, BackEnd

#52 Add assignment detail structure and routing for teacher view
  client/src/app/teacherAssignmentDetail/[assignId]/assignmentSubAnalyze.tsx
  client/src/app/teacherAssignmentDetail/[assignId]/page.tsx
  client/src/app/teacherAssignmentDetail/page.tsx
  client/src/components/teacher/assignmentItem.tsx
  client/src/components/teacher/teacheAssignmentForm.tsx
  client/src/components/teacher/teacherDashboard.tsx
Labels: FrontEnd, PineQuest

#55 update front
  client/package-lock.json
  client/package.json
  client/src/app/studentRoom/page.tsx
  client/src/app/teacherRoom/dashboard/page.tsx
  client/src/app/teacherRoom/page.tsx
  client/src/app/teacherRoom/sign-in/page.tsx
  client/src/app/teacherRoom/sign-up/page.tsx
  client/src/components/auth/sign-in.tsx
  client/src/components/auth/sign-up.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#56 Student signIn, signUp, Joinroom done
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20250914091341_make_student_room_optional/migration.sql
  server/prisma/schema.prisma
  server/src/controllers/room/joinRoom.controller.ts
  server/src/controllers/student/joinRoom.controller.ts
  server/src/controllers/student/signIn.controller.ts
  server/src/controllers/student/signUp.controller.ts
  server/src/controllers/teacher/sign-in.controller.ts
  server/src/routes/student-routes.ts
Labels: PineQuest, BackEnd, PR status Code Ready

#59 fronEnd
  client/src/app/page.tsx
  client/src/app/teacherRoom/page.tsx
  client/src/components/auth/sign-in.tsx
  client/src/components/auth/sign-up.tsx
  client/src/components/teacher/createRoom/newRoom.tsx
Labels: documentation, FrontEnd, PineQuest, PR status Code Ready

#61 boolien shalgalt hiisen
  server/src/controllers/teacher/sign-in.controller.ts
Labels: documentation, PineQuest, BackEnd, PR status Code Ready

#62 student sign up hiisen
  client/src/app/studentRoom/dashboard/page.tsx
  client/src/app/studentRoom/page.tsx
  client/src/components/auth/student/signIn.tsx
  client/src/components/auth/student/signUp.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#65 router student added login
  server/src/routes/student-routes.ts
Labels: PineQuest, BackEnd, PR status Code Ready

#69 auth design
  client/src/app/teacherRoom/page.tsx
  client/src/app/teacherRoom/sign-in/page.tsx
  client/src/app/teacherRoom/sign-up/page.tsx
  client/src/components/auth/sign-in.tsx
  client/src/components/auth/sign-up.tsx
  client/src/components/auth/teacher/sign-in.tsx
  client/src/components/auth/teacher/sign-up.tsx
Labels: documentation, FrontEnd, PineQuest, PR status Code Ready

#71 update
  client/src/app/page.tsx
  client/src/app/teacherRoom/page.tsx
  client/src/app/teacherRoom/sign-in/page.tsx
  client/src/app/teacherRoom/sign-up/page.tsx
  client/src/components/home/home.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#72 student auth with join
  client/src/app/studentRoom/joinclass/page.tsx
  client/src/app/studentRoom/page.tsx
  client/src/components/auth/student/signIn.tsx
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentJoin.tsx
Labels: student, FrontEnd, PineQuest, PR status Code Ready

#74 design zaswar
  client/src/app/teacherRoom/dashboard/page.tsx
  client/src/components/teacher/createRoom/newRoom.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#75 teacher assignments
  client/src/components/data/dummyData.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionAssignments.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionRow.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionTable.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionTableItem.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionsHeader.tsx
  client/src/components/teacher/assignmentDetail/Submissions/badge.tsx
  client/src/components/teacher/assignmentDetail/assignmentTab.tsx
  client/src/utils/utils.ts
Labels: teacher, FrontEnd, PineQuest, structure, PR status Code Ready

#76 joinclass updated
  server/src/controllers/room/joinRoom.controller.ts
  server/src/routes/student-routes.ts
Labels: student, PineQuest, BackEnd, PR status Code Ready

#78 studentroom fixed
  client/src/app/studentRoom/page.tsx
Labels: student, FrontEnd, PineQuest, PR status Code Ready

#81 student newtreh heseg roomd newtreh heseg zassan
  client/package-lock.json
  client/package.json
  client/src/app/studentRoom/page.tsx
  client/src/components/auth/student/signIn.tsx
  client/src/components/student/studentJoin.tsx
  client/src/components/ui/form.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#86 student Sign in footer ynzalsan
  client/src/components/auth/student/signIn.tsx
Labels: student, FrontEnd, PineQuest, PR status Code Ready

#92 push changed link
  client/src/components/home/home.tsx
Labels: documentation, FrontEnd, PineQuest, PR status Code Ready

#93 student burtguuleh heseg
  client/src/components/auth/student/signIn.tsx
  client/src/components/auth/student/signUp.tsx
  client/src/components/ui/alert.tsx
Labels: student, FrontEnd, PineQuest, PR status Code Ready

#94 SubmissionRow assignDialog holobson dahin zasah shaardalgtai
  client/package-lock.json
  client/src/components/teacher/assignmentDetail/Submissions/AssignDialog.tsx
  client/src/components/teacher/assignmentDetail/Submissions/OverviewDetails.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionRow.tsx
  client/src/components/teacher/assignmentDetail/components/overviewCarts.tsx
Labels: documentation, teacher, FrontEnd, PineQuest, PR status Code Ready

#101 font changed student dashboard changed
  client/src/app/globals.css
  client/src/components/auth/student/signIn.tsx
  client/src/components/auth/student/signUp.tsx
  client/src/components/home/home.tsx
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentHomeWork.tsx
Labels: student, FrontEnd, PineQuest, PR status Code Ready

#107 update schema teacher assginment, studend sub
  server/prisma/migrations/20250916015500_update_schema/migration.sql
  server/prisma/schema.prisma
  server/src/controllers/GeminiStudent/studentSubmitAnalyze.controller.ts
  server/src/controllers/teacher/CreateAssigment.controller.ts
  server/src/routes/createTeacher.ts
Labels: documentation, student, teacher, PineQuest, BackEnd, structure, PR status Code Ready, Ai

#111 studentHomeWork fixed
  client/package-lock.json
  client/package.json
  client/src/components/student/studentHomeWork.tsx
Labels: FrontEnd, PineQuest

#118 create assignment
  server/prisma/schema.prisma
  server/src/controllers/teacher/CreateAssigment.controller.ts
  server/src/routes/createTeacher.ts
Labels: FrontEnd, BackEnd

#121 assigment card holboson
  client/package-lock.json
  client/src/components/student/AssignmentCard.tsx
  client/src/components/student/StudentDashboard.tsx
Labels: FrontEnd, PineQuest, BackEnd, PR status Code Ready

#122 getAssigment controller
  server/prisma/schema.prisma
  server/src/controllers/student/getAssigment.controller.ts
  server/src/controllers/teacher/CreateAssigment.controller.ts
  server/src/routes/student-routes.ts
Labels: PineQuest, BackEnd, PR status Code Ready

#123 Student assignment backend connect
  client/package-lock.json
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentHomeWork.tsx
Labels: student, FrontEnd, PineQuest, structure, PR status Code Ready, Ai

#127 send assignment get by id dynamic student
  client/src/app/studentRoom/page.tsx
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentHomeWork.tsx
Labels: student, help wanted, FrontEnd, PineQuest, PR status Code Ready, add class

#130 teacher dashboard: classroom create/delete UI + backend connection
  client/src/app/teacherRoom/page.tsx
  client/src/components/student/studentHomeWork.tsx
  client/src/components/teacher/Assign/DeleteClassRoom.tsx
  client/src/components/teacher/Assign/addDeleteRoom.tsx
  client/src/components/teacher/Assign/assignmentItem.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
Labels: teacher, FrontEnd, PineQuest, structure, PR status Code Ready, add class, Integration

#137 stats section
  client/src/components/teacher/assignmentDetail/Stats/distribution.tsx
  client/src/components/teacher/assignmentDetail/Stats/overviewCarts.tsx
  client/src/components/teacher/assignmentDetail/assignmentTab.tsx
  client/src/components/teacher/assignmentDetail/assignmentdetailHeader.tsx
  client/src/components/teacher/teacherDashboard.tsx
Labels: teacher, FrontEnd, PineQuest, PR status Code Ready, statistic

#143 statistic section improving
  client/src/app/studentRoom/page.tsx
  client/src/app/teacherAssignmentDetail/[assignId]/assignmentSubAnalyze.tsx
  client/src/app/teacherAssignmentDetail/[assignId]/page.tsx
  client/src/components/teacher/Assign/teacheAssignmentForm.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
  client/src/components/teacher/assignmentDetail/Stats/distribution.tsx
  client/src/components/teacher/assignmentDetail/Stats/overviewCarts.tsx
  client/src/components/teacher/assignmentDetail/Submissions/AssignDialog.tsx
  client/src/components/teacher/assignmentDetail/Submissions/OverviewDetails.tsx
  client/src/components/teacher/assignmentDetail/assignmentTab.tsx
  client/src/components/teacher/assignmentDetail/assignmentdetailHeader.tsx
Labels: teacher, FrontEnd, PineQuest, PR status Code Ready, statistic

#144 bagshiin homework heseg
  client/package-lock.json
  client/package.json
  client/src/components/teacher/assignmentDetail/Submissions/AssignDialog.tsx
  client/src/components/teacher/assignmentDetail/Submissions/GurvanUildel.tsx
  client/src/components/teacher/assignmentDetail/Submissions/OverviewCards.tsx
  client/src/components/teacher/assignmentDetail/Submissions/OverviewDetails.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionAssignments.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionCarousel.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionRow.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionTable.tsx
  client/src/components/teacher/assignmentDetail/Submissions/TeacherFeedbackCard.tsx
  client/src/components/teacher/assignmentDetail/Submissions/badge.tsx
  client/src/components/teacher/assignmentDetail/assignmentTab.tsx
  client/src/components/ui/carousel.tsx
Labels: documentation, teacher, FrontEnd, PineQuest, PR status Code Ready

#146 bagsh suragch daalgawriin button zassan
  client/src/components/student/AssignmentCard.tsx
  client/src/components/teacher/Assign/assignmentItem.tsx
  client/src/components/teacher/Assign/teacheAssignmentForm.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
  client/src/types/index.tsx
Labels: student, teacher, FrontEnd, PineQuest

#149 getStudentAssignmentsByAssignmentId controller bichsen
  server/src/controllers/GeminiStudent/getStudentAssignmentsByAssignmentId.controller.ts
  server/src/controllers/room/getTeacherIdByRoom.controller.ts
  server/src/controllers/room/getassignment.controller.ts
  server/src/routes/createTeacher.ts
Labels: PineQuest, BackEnd, PR status Code Ready

#150 feedback comment
  client/src/components/student/StudentDashboard.tsx
  client/src/components/teacher/assignmentDetail/Submissions/GurvanUildel.tsx
  client/src/types/index.tsx
Labels: FrontEnd, PineQuest

#157 Add multi-assignment image upload, ui fix for students
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/components/student/studentHomeWork.tsx
  client/src/components/ui/sonner.tsx
Labels: student, FrontEnd, PineQuest, PR status Code Ready, Ai, file uploader

#159 debug teacherDashboard
  client/src/components/teacher/Assign/teacherDashboard.tsx
Labels: bug, FrontEnd, PineQuest, PR status Code Ready

#161 teacher date filtered
  client/src/components/teacher/Assign/teacherDashboard.tsx
Labels: bug, teacher, FrontEnd, PineQuest, PR status Code Ready

#165 teacher logic
  client/src/components/teacher/Assign/teacheAssignmentForm.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#167 Update student homework submission design
  client/package-lock.json
  client/package.json
  client/src/components/student/AssignmentCard.tsx
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentHomeWork.tsx
  client/src/components/ui/alert-dialog.tsx
  client/src/components/ui/button.tsx
Labels: student, FrontEnd, PineQuest, PR status Code Ready

#168 assignmentTab
  client/src/components/teacher/Assign/assignmentItem.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
  client/src/components/teacher/assignmentDetail/Submissions/GarchigDelgerengui.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionAssignments.tsx
  client/src/components/teacher/assignmentDetail/assignmentTab.tsx
Labels: teacher, FrontEnd, PineQuest, PR status Code Ready, Assignment

#170 loading
  client/src/components/student/studentHomeWork.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
  client/src/components/teacher/assignmentDetail/assignmentTab.tsx
  client/src/components/ui/loadingSpinner.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#171 zassan trash maani daragdsan tul dahiad zasaad pushillee
  client/src/components/teacher/Assign/teacherDashboard.tsx
Labels: documentation, teacher, FrontEnd, PineQuest, PR status Code Ready

#173 build
  client/src/components/student/studentHomeWork.tsx
  client/src/components/teacher/Assign/teacheAssignmentForm.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
  client/src/types/index.tsx
Labels: bug, FrontEnd

#181 student send assignment change
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentHomeWork.tsx
  client/src/components/teacher/teacherDashboard.tsx
Labels: student, FrontEnd, PineQuest, Assignment

#185 assignment controller
  server/prisma/schema.prisma
  server/src/controllers/assigments/getAssignmentwithAi.controller.ts
  server/uploads/1758276693083-Image (2).jpeg
Labels: student, teacher, PineQuest, BackEnd, PR status Code Ready

#191 uploads path nemsen
  server/src/index.ts
Labels: PineQuest, BackEnd, PR status Code Ready, Ai, Assignment

#195 submission image show front
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentHomeWork.tsx
Labels: student, teacher, FrontEnd, PineQuest, PR status Code Ready, Assignment

#196 suragchiin daalgawariin zurgiig gargadag bolson
  client/next.config.ts
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionAssignments.tsx
Labels: teacher, PineQuest, PR status Code Ready, Ai, Assignment, IMG connect

#199 teacher improvement
  client/src/components/student/StudentDashboard.tsx
  client/src/components/teacher/Assign/assignmentItem.tsx
  client/src/components/teacher/Assign/teacheAssignmentForm.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
Labels: teacher, FrontEnd, PineQuest, PR status Code Ready

#202 Analysis deer bagsh approve hiij baigaa heseg
  client/src/components/teacher/assignmentDetail/Submissions/GurvanUildel.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionAssignments.tsx
Labels: FrontEnd, PineQuest, BackEnd, PR status Code Ready, Ai, Connect to the backend, AnalysisWithScore

#206 student submission ui fix & backend
  client/src/components/student/studentHomeWork.tsx
Labels: student, teacher, FrontEnd, PineQuest, add class, file uploader, Assignment, IMG connect

#207 submission-assignment-improvement
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionAssignments.tsx
Labels: teacher, FrontEnd, PineQuest, PR status Code Ready

#208 studentScore hiisen
  client/src/components/student/AssignmentCard.tsx
  client/src/components/student/StudentDashboard.tsx
  client/src/types/index.tsx
Labels: student, FrontEnd, PineQuest, PR status Code Ready, Ai, Assignment, AnalysisWithScore

#211 bug
  client/src/components/student/StudentDashboard.tsx
  client/src/components/student/studentHomeWork.tsx
  client/src/types/index.tsx
Labels: bug, FrontEnd

#216 Teacher dashboard: mark assignments as reviewed/unreviewed
  client/src/components/student/studentHomeWork.tsx
  client/src/components/teacher/Assign/AssignmentList.tsx
  client/src/components/teacher/Assign/assignmentItem.tsx
  client/src/components/teacher/Assign/teacheAssignmentForm.tsx
  client/src/components/teacher/Assign/teacherDashboard.tsx
  client/src/types/index.tsx
Labels: teacher, FrontEnd, structure, Assignment, Connect to the backend

#217 Backend:mark assignments as checked & merge AI with submissions
  server/src/controllers/allSubmissions/getAllSubByAssignmentId.controller.ts
  server/src/controllers/allSubmissions/getAllSubmissions.controller.ts
  server/src/controllers/assigments/assignment.controller.ts
  server/src/controllers/assigments/getStudentSubmissionByAssignId.controller.ts
  server/src/controllers/student/submission.controller.ts
  server/src/controllers/teacher/TeacherisChecked.controller.ts
  server/src/index.ts
  server/src/routes/allSub.router.ts
  server/src/routes/assigment.router.ts
  server/src/routes/teacher.ts
Labels: teacher, PineQuest, BackEnd, PR status Code Ready, Assignment

#223 student join room
  client/src/app/studentJoinRoom/page.tsx
  client/src/components/auth/student/StudentJoinRoom.tsx
  client/src/components/home/home.tsx
  client/src/components/student/StudentDashboard.tsx
  client/src/components/ui/loadingSpinner.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#224 student Join Room controller
  server/prisma/schema.prisma
  server/src/controllers/room/studentJoinRoom.controller.ts
  server/src/routes/room-routes.ts
Labels: PineQuest, BackEnd, PR status Code Ready

#225 studentJoin build
  client/src/components/auth/student/StudentJoinRoom.tsx
Labels: FrontEnd, PineQuest, PR status Code Ready

#226 roomName, title bolon description hesgiin holbson
  client/src/app/teacherAssignmentDetail/[assignId]/assignmentSubAnalyze.tsx
  client/src/app/teacherAssignmentDetail/[assignId]/page.tsx
  client/src/components/teacher/Assign/AssignmentList.tsx
  client/src/components/teacher/Assign/ClassroomList.tsx
  client/src/components/teacher/Assign/assignmentItem.tsx
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionAssignments.tsx
  client/src/components/teacher/assignmentDetail/assignmentTab.tsx
  client/src/components/teacher/assignmentDetail/assignmentdetailHeader.tsx
Labels: documentation, teacher, FrontEnd, PineQuest, PR status Code Ready

#227 getAllSubByAssignmentId.controller.ts
  server/src/controllers/allSubmissions/getAllSubByAssignmentId.controller.ts
Labels: documentation, PineQuest, BackEnd, PR status Code Ready

#236 teacher sign-up
  server/src/controllers/teacher/sign-up.controller.ts
  server/src/index.ts
Labels: PineQuest, BackEnd, PR status Code Ready

#238 assigmentSubAnalyze hesgiin build aldaa zassan
  client/src/app/teacherAssignmentDetail/[assignId]/assignmentSubAnalyze.tsx
Labels: bug, FrontEnd

#277 status
  server/src/controllers/GeminiStudent/studentSubmitAnalyze.controller.ts
Labels: BackEnd

#278 teacher
  client/src/components/teacher/assignmentDetail/Submissions/SubmissionAssignments.tsx
Labels: FrontEnd
